<!-- src/views/Matrix.vue -->
<template>
    <div class="matrix-container">
      <h1 class="main-title">Matrices</h1>
      <p class="intro">
        A matrix is a two-dimensional array of numbers arranged in rows and columns. Matrices are used to represent mathematical concepts and can be used in various applications, including graphics and data processing.
      </p>
  
      <h2 class="sub-title">Key Characteristics of Matrices</h2>
      <ul class="characteristics-list">
        <li><strong>Rectangular shape:</strong> Matrices can be of any size, defined by rows and columns.</li>
        <li><strong>Homogeneous elements:</strong> All elements in a matrix must be of the same data type.</li>
        <li><strong>Access by row and column:</strong> Elements can be accessed using their row and column indices.</li>
      </ul>
  
      <h2 class="sub-title">Diagram of a Matrix</h2>
      <img src="@/assets/matrix-diagram.jpeg" alt="Matrix Diagram" class="matrix-diagram"/>
  
      <h2 class="sub-title">Introduction to Matrices</h2>
      <p>Matrices are widely used in mathematics and its applications. They can be manipulated using various operations, making them fundamental in linear algebra.</p>
  
      <h2 class="sub-title">Types of Matrices</h2>
      <h3 class="type-title">Row Matrix</h3>
      <p>A matrix with a single row.</p>
  
      <h3 class="type-title">Column Matrix</h3>
      <p>A matrix with a single column.</p>
  
      <h3 class="type-title">Square Matrix</h3>
      <p>A matrix with the same number of rows and columns.</p>
  
      <h2 class="sub-title">Matrix Operations</h2>
      <p>Common operations performed on matrices include addition, subtraction, multiplication, and finding the determinant.</p>
  
      <h2 class="sub-title">Adjoint and Inverse of a Matrix</h2>
      <p>The adjoint of a matrix is the transpose of its cofactor matrix, while the inverse is the matrix that, when multiplied with the original, yields the identity matrix.</p>
  
      <h2 class="sub-title">Rank of a Matrix and Special Matrices</h2>
      <p>The rank of a matrix is the dimension of the vector space generated by its rows or columns. Special matrices include diagonal, identity, and zero matrices.</p>
  
      <h2 class="sub-title">Solving Linear Equations Using Matrix</h2>
      <p>Matrices can be used to represent and solve systems of linear equations through methods like Gaussian elimination and matrix inversion.</p>
  
      <h2 class="sub-title">Examples</h2>
      <p>Click on the buttons below to see examples of matrices in different programming languages:</p>
      
      <div class="button-container">
        <button @click="showExample('java')" class="example-button">Example in Java</button>
        <button @click="showExample('c')" class="example-button">Example in C</button>
        <button @click="showExample('python')" class="example-button">Example in Python</button>
      </div>
      
      <pre v-if="exampleCode">
        <code>{{ exampleCode }}</code>
      </pre>
  
      <h2 class="sub-title">Useful Links</h2>
      <h3 class="link-title">YouTube Tutorials</h3>
      <ul>
        <li><a href="https://www.youtube.com/watch?v=abc123" target="_blank">Matrices in JavaScript (English)</a></li>
        <li><a href="https://www.youtube.com/watch?v=xyz456" target="_blank">Matrices in Hindi</a></li>
      </ul>
    </div>
  </template>
  
  <script>
  export default {
    name: "Matrix",
    data() {
      return {
        exampleCode: "",
      };
    },
    methods: {
      showExample(language) {
        if (language === 'java') {
          this.exampleCode = `// Declaration of a matrix in Java
  int[][] matrix = {
      {1, 2, 3},
      {4, 5, 6},
      {7, 8, 9}
  };
  // Accessing elements
  System.out.println(matrix[0][0]); // Output: 1`;
        } else if (language === 'c') {
          this.exampleCode = `// Declaration of a matrix in C
  int matrix[3][3] = {
      {1, 2, 3},
      {4, 5, 6},
      {7, 8, 9}
  };
  // Accessing elements
  printf("%d", matrix[0][0]); // Output: 1`;
        } else if (language === 'python') {
          this.exampleCode = `# Declaration of a matrix in Python
  matrix = [
      [1, 2, 3],
      [4, 5, 6],
      [7, 8, 9]
  ]
  # Accessing elements
  print(matrix[0][0])  # Output: 1`;
        }
      },
    },
  };
  </script>
  
  <style scoped>
  .matrix-container {
    max-width: 800px;
    margin: 20px auto;
    padding: 20px;
    border-radius: 10px;
    background-color: #121212; /* Dark background color */
    box-shadow: 0 4px 20px rgba(0, 0, 0, 0.6);
    font-family: 'Roboto', sans-serif; /* Updated font */
    color: #e0e0e0; /* Light text color for better readability */
    line-height: 1.6; /* Increased line height for better readability */
  }
  
  .main-title {
    font-size: 2.8em; /* Larger font size for main title */
    color: #f8f8f8; /* Bright color for the main title */
    text-align: center;
    margin-bottom: 30px; /* Increased margin for better spacing */
  }
  
  .sub-title {
    font-size: 2em; /* Larger font size for sub-titles */
    color: #e0ce46; /* Bright color for sub-titles */
    margin-top: 40px; /* Increased margin for better spacing */
    padding-bottom: 10px; /* Space below the sub-title */
  }
  
  .type-title {
    font-size: 1.8em; /* Larger font size for type titles */
    color: #e0ce46; /* Bright color for type titles */
    margin-top: 25px; /* Margin for type titles */
  }
  
  .intro {
    font-size: 1.3em; /* Increased font size for intro text */
    margin-bottom: 25px; /* Increased margin for better spacing */
  }
  
  .characteristics-list {
    margin: 10px 0;
    padding-left: 20px;
    font-size: 1.2em; /* Increased font size for list items */
  }
  
  li {
    margin-bottom: 15px; /* Increased margin for list items */
    line-height: 1.6; /* Increased line height for better readability */
  }
  
  .matrix-diagram {
    width: 100%;
    height: auto;
    margin: 30px 0; /* Increased margin for better spacing */
    border: 1px solid #444; /* Darker border for image */
    border-radius: 5px;
  }
  
  pre {
    background-color: #1f1f1f; /* Darker background for code */
    padding: 10px;
    border-radius: 5px;
    overflow-x: auto; /* Allow horizontal scrolling for long code */
    color: #00ff00; /* Green text color for code */
  }
  
  .button-container {
    display: flex;
    justify-content: space-around; /* Space buttons evenly */
    margin: 30px 0; /* Increased margin for better spacing */
  }
  
  .example-button {
    background-color: #e0ce46; /* Button color */
    color: #121212; /* Text color */
    border: none;
    border-radius: 5px;
    padding: 15px 30px; /* Increased padding for better click area */
    font-size: 1.5em; /* Increased font size for buttons */
    cursor: pointer;
    transition: background-color 0.3s;
  }
  
  .example-button:hover {
    background-color: #f6f361; /* Change color on hover */
  }
  
  a {
    color: #ddc452; /* Link color */
    text-decoration: none; /* Remove underline */
    font-size: 1.2em; /* Increased font size for links */
  }
  
  a:hover {
    text-decoration: underline; /* Underline on hover */
  }
  
  .link-title {
    color: #ffffff; /* Bright color for link titles */
    margin-top: 20px; /* Space above link titles */
    font-size: 1.5em; /* Increased font size for link titles */
  }
  </style>
  