<template>
  <div class="quiz-container">
    <!-- Navigation Header -->
    <div class="nav-header">
      <button @click="goBack" class="back-button">
        <span class="back-icon">←</span>
        Back to Dashboard
      </button>
    </div>

    <!-- Main Content -->
    <div class="quiz-content">
      <div class="header-section">
        <h1 class="main-title">Choose Your Quiz Type</h1>
        <p class="subtitle">Select the type of quiz you'd like to take</p>
      </div>

      <div class="quiz-cards-container">
        <div class="quiz-cards">
          <!-- Topic Wise Quiz Card -->
          <div class="quiz-card" @click="goToTopicWiseQuiz">
            <div class="card-content">
              <div class="card-icon">📚</div>
              <h2>Topic Wise Quiz</h2>
              <p>Practice questions organized by specific topics and concepts</p>
              <div class="card-stats">
                <div class="stat">
                  <span class="stat-value">5+</span>
                  <span class="stat-label">Topics</span>
                </div>
                <div class="stat">
                  <span class="stat-value">50+</span>
                  <span class="stat-label">Questions</span>
                </div>
              </div>
              <button class="start-button">
                Start Quiz
                <span class="arrow">→</span>
              </button>
            </div>
          </div>

          <!-- AI Generated Topic Wise Quiz Card -->
          <div class="quiz-card" @click="goToAIGeneratedQuiz">
            <div class="card-content">
              <div class="card-icon">🤖</div>
              <h2>AI Generated Topic-Wise Quiz</h2>
              <p>
                All questions are generated by AI with three difficulty levels: 
                <strong>Level 1</strong>, <strong>Level 2</strong>, and <strong>Level 3</strong>.
              </p>
              <div class="card-stats">
                <div class="stat">
                  <span class="stat-value">3+</span>
                  <span class="stat-label">Difficulty Levels</span>
                </div>
                <div class="stat">
                  <span class="stat-value">50+</span>
                  <span class="stat-label">Questions</span>
                </div>
              </div>
              <button class="start-button">
                Start Quiz
                <span class="arrow">→</span>
              </button>
            </div>
          </div>

          
          <!-- Company Specific Card -->
          <div class="quiz-card" @click="goToCompanySpecific">
            <div class="card-content">
              <div class="card-icon">💼</div>
              <h2>Company Specific</h2>
              <p>Practice coding questions from top tech companies</p>
              <div class="card-stats">
                <div class="stat">
                  <span class="stat-value">10+</span>
                  <span class="stat-label">Companies</span>
                </div>
                <div class="stat">
                  <span class="stat-value">100+</span>
                  <span class="stat-label">Questions</span>
                </div>
              </div>
              <button class="start-button">
                Start Quiz
                <span class="arrow">→</span>
              </button>
            </div>
          </div>

          
        </div>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  name: "QuizOptions",
  methods: {
    goToCompanySpecific() {
      this.$router.push({ name: "company-specific" });
    },
    goToTopicWiseQuiz() {
      this.$router.push({ name: "topic-wise-quiz" });
    },
    goToAIGeneratedQuiz() {
      this.$router.push({ name: "aitopicwise" });
    },
    goBack() {
      this.$router.push({ name: 'Dashboard' });
    }
  }
};
</script>


<style scoped>
.quiz-container {
  min-height: 100vh;
  background: linear-gradient(135deg, #000000 0%, #393939 100%);
  padding: 2rem;
}

.nav-header {
  max-width: 1200px;
  margin: 0 auto 2rem;
}

.back-button {
  display: flex;
  align-items: center;
  gap: 0.5rem;
  background: white;
  border: 1px solid #e2e8f0;
  padding: 0.75rem 1.5rem;
  border-radius: 8px;
  color: #1e293b;
  font-weight: 500;
  cursor: pointer;
  transition: all 0.2s ease;
}

.back-button:hover {
  background: #f1f5f9;
  transform: translateX(-4px);
}

.back-icon {
  font-size: 1.2rem;
}

.quiz-content {
  max-width: 1200px;
  margin: 0 auto;
}

.header-section {
  text-align: center;
  margin-bottom: 3rem;
}

.main-title {
  font-size: 2.5rem;
  font-weight: 700;
  color: #d6d7d7;
  margin-bottom: 0.5rem;
}

.subtitle {
  color: #cacaca;
  font-size: 1.1rem;
}

.quiz-cards-container {
  overflow-x: auto;
  padding-bottom: 1rem;
}

.quiz-cards {
  display: flex;
  gap: 2rem;
  min-width: min-content;
  margin: 0 auto;
}

.quiz-card {
  flex: 0 0 350px;
  background: rgb(251, 251, 251);
  border-radius: 16px;
  overflow: hidden;
  box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06);
  cursor: pointer;
  transition: all 0.3s ease;
}

.quiz-card:hover {
  transform: translateY(-8px);
  box-shadow: 0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04);
}

.card-content {
  padding: 2rem;
}

.card-icon {
  font-size: 2.5rem;
  margin-bottom: 1.5rem;
}

.quiz-card h2 {
  color: #1e293b;
  font-size: 1.5rem;
  font-weight: 600;
  margin-bottom: 0.75rem;
}

.quiz-card p {
  color: #64748b;
  margin-bottom: 1.5rem;
  line-height: 1.5;
}

.card-stats {
  display: flex;
  justify-content: space-around;
  margin-bottom: 1.5rem;
  padding: 1rem 0;
  border-top: 1px solid #e2e8f0;
  border-bottom: 1px solid #e2e8f0;
}

.stat {
  text-align: center;
}

.stat-value {
  display: block;
  font-size: 1.5rem;
  font-weight: 700;
  color: #0061fe;
}

.stat-label {
  font-size: 0.875rem;
  color: #64748b;
}

.start-button {
  width: 100%;
  padding: 0.75rem;
  background-color: #001aff;
  color: white;
  border: none;
  border-radius: 8px;
  font-weight: 500;
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 0.5rem;
  cursor: pointer;
  transition: all 0.2s ease;
}

.start-button:hover {
  background-color: #000000;
}

.arrow {
  transition: transform 0.2s ease;
}

.start-button:hover .arrow {
  transform: translateX(4px);
}

@media (max-width: 1200px) {
  .quiz-cards {
    padding: 0 1rem;
  }
}

@media (max-width: 768px) {
  .quiz-container {
    padding: 1rem;
  }

  .main-title {
    font-size: 2rem;
  }

  .quiz-card {
    flex: 0 0 300px;
  }

  .card-content {
    padding: 1.5rem;
  }
}
</style>